#!/bin/bash
#training
read -p "Package name : " name
clear
if apt-cache show $name
then
	read -p "Attributrs : " attributrs
	if apt-cache show $name| cut -d" " -f-1|sort|uniq|grep -w $attributrs":"
	then
		if echo Tag |grep -w $attributrs
		then
			clear
			apt-cache show $name |grep ::
		else
			if echo Description |grep -w $attributrs
			then
				clear
				echo "Not have Attributrs: $attributrs"
			else
				if echo en |grep -w $attributrs
				then 
					clear
					echo "Not have Attributrs: $attributrs"
				else
					if echo Description-en |grep -w $attributrs
					then
						clear
						apt-cache show $name| grep -w "Description-en"
						apt-cache show $name| grep  "^ "|grep -v "::"

					else	
						if echo Installed |grep -w $attributrs
						then 
							clear
							echo "Not have Attributrs: Installed"
						else
							if echo Size |grep -w $attributrs
							then 
								clear
								apt-cache show $name |grep -w Size |tail -1
							else	
								if echo Arch |grep -w $attributrs
								then
									clear
									echo "Not have Attributrs: $attributrs"
								else
									if echo Essential |grep -w $attributrs
									then
										clear
										echo "Not have Attributrs: $attributrs"
									else
										if echo Depends|grep -w $attributrs
										then
											clear 
											apt-cache show $name| grep -w $attributrs|head -1
										else
											if echo md5 |grep -w $attributrs
											then 
												clear
												echo "Not have Attributrs: $attributrs"
											else
												clear	
												apt-cache show $name |grep -w $attributrs
											fi
										fi
									fi
								fi				
							fi
						fi
					fi
				fi
			fi
		fi
	else
		clear
		echo "Not have Attributrs: $attributrs"
	fi
else
	clear
	echo "Not have Package: $name"

	
fi
